name: open_gate
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  auto_route: ^4.0.1
  csv: ^5.0.1
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  file_picker: ^4.6.1
  flutter:
    sdk: flutter
  flutter_svg: ^1.1.1+1
  freezed_annotation: ^2.0.3
  get: ^4.6.5
  google_fonts: ^3.0.1
  hive: ^2.2.2
  hive_flutter: ^1.1.0
  iconly: ^1.0.1
  iconsax: ^0.0.8
  json_annotation: ^4.5.0
  skeletons: ^0.0.3

dev_dependencies:
  auto_route_generator: ^4.0.0
  build_runner: ^2.1.11
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.0.3+1
  hive_generator: ^1.1.3
  json_serializable: ^6.2.0
  lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
